export const dynamic = "force-dynamic";

import Link from "next/link";
import { Coins, Share2, Users } from "lucide-react";

import { getReferralOverview, getBackupsSettings } from "../../../lib/admin-data";
import { fmtDate, integer, money } from "../../../lib/format";

function Stat({ label, value, detail, Icon }) {
  return (
    <div className="stat">
      <div style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center" }}>
        <span className="muted">{label}</span>
        {Icon ? <Icon size={18} /> : null}
      </div>
      <strong>{value}</strong>
      <div className="muted">{detail}</div>
    </div>
  );
}

export default async function ReferralsPage() {
  const [overview, settings] = await Promise.all([
    getReferralOverview(),
    getBackupsSettings(),
  ]);

  const percent = Number(settings.referral_commission_percent || 10) || 10;

  return (
    <div className="grid" style={{ gap: 16 }}>
      <div className="toolbar">
        <div>
          <h2 style={{ margin: 0 }}>Referrals</h2>
          <div className="muted">First referral link wins. Every later external payment can credit the referrer wallet.</div>
        </div>
        <div className="actions">
          <Link className="btn secondary" href="/admin/settings">Adjust commission</Link>
        </div>
      </div>

      <div className="grid cards">
        <Stat label="Commission rate" value={`${percent}%`} detail="Applied to confirmed external payments" Icon={Coins} />
        <Stat label="Referral links used" value={overview.summary.totalReferrals} detail={`${overview.summary.activeReferrers} hosts have at least one referral`} Icon={Share2} />
        <Stat
          label="Commission paid"
          value={`$${money(overview.summary.totalCommissionUsdt)}`}
          detail={`${integer(overview.summary.totalCommissionToman)} Toman credited in total`}
          Icon={Users}
        />
      </div>

      <section className="section">
        <div className="toolbar">
          <div>
            <h2 style={{ margin: 0 }}>Referrer performance</h2>
            <div className="muted">How many people each host brought in and how much was credited to the wallet.</div>
          </div>
        </div>
        <div className="card-list">
          {overview.hosts.length ? overview.hosts.map((host) => (
            <div key={host.id} className="item">
              <div className="item-head">
                <div>
                  <h3 className="item-title wrap">{host.first_name || host.username || `User ${host.telegram_id}`}</h3>
                  <p className="item-sub wrap">
                    @{host.username || "unknown"} · Telegram {host.telegram_id}
                    {host.referral_code ? ` · code ${host.referral_code}` : ""}
                  </p>
                </div>
                <Link className="btn ghost" href={`/admin/customers/${host.id}`}>Open customer</Link>
              </div>
              <div className="grid cards" style={{ marginTop: 12, gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))" }}>
                <div className="stat" style={{ minHeight: 0 }}>
                  <span className="muted">Total referrals</span>
                  <strong style={{ fontSize: 18 }}>{host.total_referrals}</strong>
                </div>
                <div className="stat" style={{ minHeight: 0 }}>
                  <span className="muted">Converted</span>
                  <strong style={{ fontSize: 18 }}>{host.converted_referrals}</strong>
                </div>
                <div className="stat" style={{ minHeight: 0 }}>
                  <span className="muted">Earned USD</span>
                  <strong style={{ fontSize: 18 }}>${money(host.earned_usdt)}</strong>
                </div>
                <div className="stat" style={{ minHeight: 0 }}>
                  <span className="muted">Earned Toman</span>
                  <strong style={{ fontSize: 18 }}>{integer(host.earned_toman)} Toman</strong>
                </div>
              </div>
            </div>
          )) : <div className="muted">No referral data yet.</div>}
        </div>
      </section>

      <section className="section">
        <div className="toolbar">
          <div>
            <h2 style={{ margin: 0 }}>Recent commissions</h2>
            <div className="muted">Newest wallet credits generated by referred customer payments.</div>
          </div>
        </div>
        <div className="card-list">
          {overview.recent.length ? overview.recent.map((entry) => (
            <div key={entry.id} className="item">
              <div className="item-head">
                <div>
                  <h3 className="item-title wrap">{entry.order_id || `Payment ${entry.payment_id}`}</h3>
                  <p className="item-sub wrap">
                    Host: {entry.referrer_first_name || entry.referrer_username || `User ${entry.referrer_telegram_id}`}
                    {" · "}
                    Referred: {entry.referred_first_name || entry.referred_username || `User ${entry.referred_telegram_id}`}
                  </p>
                </div>
                <span className="pill ok">{entry.percent}%</span>
              </div>
              <p className="item-sub wrap" style={{ marginTop: 8 }}>
                ${money(entry.amount_usdt)} · {integer(entry.amount_toman)} Toman · {fmtDate(entry.created_at)}
              </p>
            </div>
          )) : <div className="muted">No referral commissions recorded yet.</div>}
        </div>
      </section>
    </div>
  );
}
